site_name: Testando
theme:
  name: 'material'

repo_name: 'rafaelcorsi/mkdocs-progress'
repo_url: 'https://github.com/rafaelcorsi/mkdocs-progress/'
docs_dir: docs-src
site_dir: docs

# Copyright
copyright: 'Copyright &copy; Rafael Corsi @ insper'

nav:
- Home: index.md

#####################################################################
extra_css:
  - css/progress.css
  - 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'

extra_javascript:
  - 'js/progress.js'

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite
  - pymdownx.magiclink
  - pymdownx.details
